let songs = [
    { id: 1, name: "Sample Song 1", artist: "Artist 1", thumbnail: "path_to_img1.jpg", url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3", buyLink: "http://buySong1.com" },
    { id: 2, name: "Sample Song 2", artist: "Artist 2", thumbnail: "path_to_img2.jpg", url: "http://techslides.com/demos/samples/sample.mp3", buyLink: "http://buySong2.com" },
    { id: 3, name: "Sample Song 3", artist: "Artist 3", thumbnail: "path_to_img3.jpg", url: "path_to_song3.mp3", buyLink: "http://buySong3.com" },
    { id: 4, name: "Sample Song 4", artist: "Artist 4", thumbnail: "path_to_img4.jpg", url: "path_to_song4.mp3", buyLink: "http://buySong4.com" },
    { id: 5, name: "Sample Song 5", artist: "Artist 5", thumbnail: "path_to_img5.jpg", url: "path_to_song5.mp3", buyLink: "http://buySong5.com" },
    { id: 6, name: "Sample Song 6", artist: "Artist 6", thumbnail: "path_to_img6.jpg", url: "path_to_song6.mp3", buyLink: "http://buySong6.com" },
    { id: 7, name: "Sample Song 7", artist: "Artist 7", thumbnail: "path_to_img7.jpg", url: "path_to_song7.mp3", buyLink: "http://buySong7.com" },
    { id: 8, name: "Sample Song 8", artist: "Artist 8", thumbnail: "path_to_img8.jpg", url: "path_to_song8.mp3", buyLink: "http://buySong8.com" },
    { id: 9, name: "Sample Song 9", artist: "Artist 9", thumbnail: "path_to_img9.jpg", url: "path_to_song9.mp3", buyLink: "http://buySong9.com" },
    { id: 10, name: "Sample Song 10", artist: "Artist 10", thumbnail: "path_to_img10.jpg", url: "path_to_song10.mp3", buyLink: "http://buySong10.com" },
    { id: 11, name: "Sample Song 11", artist: "Artist 11", thumbnail: "path_to_img11.jpg", url: "path_to_song11.mp3", buyLink: "http://buySong11.com" },
    { id: 12, name: "Sample Song 12", artist: "Artist 12", thumbnail: "path_to_img12.jpg", url: "path_to_song12.mp3", buyLink: "http://buySong12.com" },
    { id: 13, name: "Sample Song 13", artist: "Artist 13", thumbnail: "path_to_img13.jpg", url: "path_to_song13.mp3", buyLink: "http://buySong13.com" },
    { id: 14, name: "Sample Song 14", artist: "Artist 14", thumbnail: "path_to_img14.jpg", url: "path_to_song14.mp3", buyLink: "http://buySong14.com" },
    { id: 15, name: "Sample Song 15", artist: "Artist 15", thumbnail: "path_to_img15.jpg", url: "path_to_song15.mp3", buyLink: "http://buySong15.com" },
    { id: 16, name: "Sample Song 16", artist: "Artist 16", thumbnail: "path_to_img16.jpg", url: "path_to_song16.mp3", buyLink: "http://buySong16.com" },
    { id: 17, name: "Sample Song 17", artist: "Artist 17", thumbnail: "path_to_img17.jpg", url: "path_to_song17.mp3", buyLink: "http://buySong17.com" },
    { id: 18, name: "Sample Song 18", artist: "Artist 18", thumbnail: "path_to_img18.jpg", url: "path_to_song18.mp3", buyLink: "http://buySong18.com" },
    { id: 19, name: "Sample Song 19", artist: "Artist 19", thumbnail: "path_to_img19.jpg", url: "path_to_song19.mp3", buyLink: "http://buySong19.com" },
    { id: 20, name: "Sample Song 20", artist: "Artist 20", thumbnail: "path_to_img20.jpg", url: "path_to_song20.mp3", buyLink: "http://buySong20.com" }
];
